# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Spring Configuration
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/aftas_security?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
  security:
    user:
      name: admin
      password: admin


jwt:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351


